# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20170716_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='like_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 18, 4, 32, 27, 485105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 18, 4, 32, 27, 485749, tzinfo=utc)),
        ),
    ]
