# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20170718_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 18, 5, 1, 18, 647921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 18, 5, 1, 18, 648578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='Post.Post'),
        ),
    ]
