# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 08:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_since', models.DateField(default=datetime.datetime(2017, 7, 13, 8, 50, 44, 579653, tzinfo=utc))),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 13, 8, 50, 44, 579000, tzinfo=utc)),
        ),
    ]
