# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0003_auto_20170713_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 13, 52, 23, 31423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 13, 52, 23, 32036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 13, 52, 23, 32617, tzinfo=utc)),
        ),
    ]
