# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0004_auto_20170716_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested_user_username',
            field=models.CharField(default='vm', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='requesting_user_username',
            field=models.CharField(default='vm', max_length=20),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 14, 30, 16, 393582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 14, 30, 16, 394317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 14, 30, 16, 395131, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set([('requesting_user_username', 'requested_user_username')]),
        ),
    ]
