# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0007_auto_20170716_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 14, 49, 22, 262261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 14, 49, 22, 262871, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 14, 49, 22, 263592, tzinfo=utc)),
        ),
    ]
