# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0008_auto_20170716_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 15, 27, 23, 48455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 15, 27, 23, 49058, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 15, 27, 23, 49779, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='request',
            name='requested_user_username',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requesting_user_username',
        ),
    ]
