# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Connection', '0011_auto_20170716_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 16, 12, 33, 237725, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 16, 12, 33, 238359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 16, 16, 12, 33, 239114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
