# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Connection', '0013_auto_20170716_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 17, 9, 11, 5, 316729, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_since',
            field=models.DateField(default=datetime.datetime(2017, 7, 17, 9, 11, 5, 317393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 17, 9, 11, 5, 318148, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([('user', 'follower')]),
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together=set([('user', 'following_user')]),
        ),
    ]
