# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_auto_20170713_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 17, 19, 33, 26, 219040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Post'),
        ),
    ]
