# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0007_auto_20170717_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('commented_at',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 17, 20, 48, 9, 964996, tzinfo=utc)),
        ),
    ]
